//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Execute.Data.SQL.SP_Execute.DataModel.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MKT_DOCENTE_CURSO_TEMP
    {
        public int ID { get; set; }
        public int DOC_ID { get; set; }
        public int LAN_ID { get; set; }
        public int MKT_ID { get; set; }
        public Nullable<System.DateTime> DCU_FEC { get; set; }
    }
}
